- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunVector
  name: vector safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunVector45ACP
      amount: 2
    - id: Magazine45ACPSubMachineGun
      amount: 4
