# Base spawner and lootspawner

- type: entity
  name: spawner
  abstract: true
  id: BaseSpawnerGuns
  parent: BaseSpawner
  components:
  - type: Sprite
    layers:
    - state: blue
    - sprite: Objects\Weapons\Guns\Pistols\N1984.rsi
      state: icon

# Explosives

- type: entity
  name: spawner
  abstract: true
  id: BaseSpawnerExplosives
  parent: BaseSpawner
  components:
  - type: Sprite
    layers:
    - state: blue
    - sprite: Objects/Weapons/Grenades/grenade.rsi
      state: icon
