- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  result: Stunbaton
  category: Weapons
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: Truncheon
  result: Truncheon
  category: Weapons
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: CombatKnife
  result: CombatKnife
  category: Weapons
  completetime: 2
  materials:
    Steel: 250
    Plastic: 100

- type: latheRecipe
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  category: Weapons
  completetime: 8
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  category: Weapons
  completetime: 5
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  category: Weapons
  completetime: 5
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  category: Weapons
  completetime: 5
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  category: Weapons
  completetime: 5
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  result: ShellShotgunBeanbag
  category: Ammo
  completetime: 2
  materials:
    Plastic: 15
    Steel: 10

- type: latheRecipe
  id: Cartridge9x19Rubber
  result: Cartridge9x19Rubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: Cartridge44MagnumRubber
  result: Cartridge44MagnumRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: Cartridge556x45
  result: Cartridge556x45
  category: Ammo
  completetime: 2
  materials:
    Steel: 15

- type: latheRecipe
  id: Cartridge762x39Rubber
  result: Cartridge762x39Rubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: Cartridge556x45Rubber
  result: Cartridge556x45Rubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: Cartridge9x19
  result: Cartridge9x19
  category: Ammo
  completetime: 2
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  result: ShellShotgun
  category: Ammo
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: ShellShotgunSlug
  result: ShellShotgunSlug
  completetime: 2
  materials:
    Steel: 25

- type: latheRecipe
  id: Cartridge44Magnum
  result: Cartridge44Magnum
  category: Ammo
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: Cartridge762x39
  result: Cartridge762x39
  category: Ammo
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: ShellShotgunFlare
  result: ShellShotgunFlare
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5

- type: latheRecipe
  id: ShellTranquilizer
  result: ShellTranquilizer
  category: Ammo
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5
    Plasma: 10
    Silver: 5

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetClown
  result: TargetClown
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetSyndicate
  result: TargetSyndicate
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: Magazine9x19
  result: Magazine9x19
  category: Ammo
  completetime: 5
  materials:
    Steel: 100

- type: latheRecipe
  id: Magazine9x19SubMachineGun
  result: Magazine9x19SubMachineGun
  category: Ammo
  completetime: 5
  materials:
    Steel: 300

- type: latheRecipe
  id: Magazine9x19SubMachineGunTopMounted
  result: Magazine9x19SubMachineGunTopMounted
  category: Ammo
  completetime: 5
  materials:
    Steel: 300

- type: latheRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  category: Ammo
  completetime: 5
  materials:
    Steel: 650

- type: latheRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  category: Ammo
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: Magazine556x45
  result: Magazine556x45
  category: Ammo
  completetime: 5
  materials:
    Steel: 375

- type: latheRecipe
  id: Magazine762x39
  result: Magazine762x39
  category: Ammo
  completetime: 5
  materials:
    Steel: 375

- type: latheRecipe
  id: MagazineBoxRifle
  result: MagazineBoxRifle
  category: Ammo
  completetime: 5
  materials:
    Steel: 950

- type: latheRecipe
  id: MagazineBoxRifleRubber
  result: MagazineBoxRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: MagazineBox762x39
  result: MagazineBox762x39
  category: Ammo
  completetime: 5
  materials:
    Steel: 1800

- type: latheRecipe
  id: MagazineBox762x39Rubber
  result: MagazineBox762x39Rubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  category: Ammo
  completetime: 5
  materials:
    Steel: 200

- type: latheRecipe
  id: ShellShotgunIncendiary
  result: ShellShotgunIncendiary
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: Cartridge9x19Incendiary
  result: Cartridge9x19Incendiary
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10

- type: latheRecipe
  id: Cartridge44MagnumIncendiary
  result: Cartridge44MagnumIncendiary
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: Cartridge762x39Incendiary
  result: Cartridge762x39Incendiary
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: Cartridge556x45Incendiary
  result: Cartridge556x45Incendiary
  category: Ammo
  completetime: 2
  materials:
    Plastic: 15

- type: latheRecipe
  id: MagazineBoxPistolIncendiary
  result: MagazineBoxPistolIncendiary
  category: Ammo
  completetime: 5
  materials:
    Plastic: 650

- type: latheRecipe
  id: MagazineBoxMagnumIncendiary
  result: MagazineBoxMagnumIncendiary
  category: Ammo
  completetime: 5
  materials:
    Plastic: 1250

- type: latheRecipe
  id: MagazineBox762x39Incendiary
  result: MagazineBox762x39Incendiary
  category: Ammo
  completetime: 5
  materials:
    Plastic: 1800

- type: latheRecipe
  id: MagazineBoxRifleIncendiary
  result: MagazineBoxRifleIncendiary
  category: Ammo
  completetime: 5
  materials:
    Plastic: 950

- type: latheRecipe
  id: ShellShotgunPractice
  result: ShellShotgunPractice
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: MagazineBoxPistolPractice
  result: MagazineBoxPistolPractice
  category: Ammo
  completetime: 5
  materials:
    Plastic: 600

- type: latheRecipe
  id: MagazineBoxMagnumPractice
  result: MagazineBoxMagnumPractice
  category: Ammo
  completetime: 5
  materials:
    Plastic: 1200

- type: latheRecipe
  id: MagazineBox762x39Practice
  result: MagazineBox762x39Practice
  category: Ammo
  completetime: 5
  materials:
    Plastic: 1000

- type: latheRecipe
  id: MagazineBoxRiflePractice
  result: MagazineBoxRiflePractice
  category: Ammo
  completetime: 5
  materials:
    Plastic: 900

- type: latheRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  category: Weapons
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  category: Weapons
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  id: ShellShotgunUranium
  result: ShellShotgunUranium
  category: Ammo
  completetime: 2
  materials:
    Plastic: 15
    Uranium: 10

- type: latheRecipe
  id: Cartridge9x19Uranium
  result: Cartridge9x19Uranium
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Uranium: 10

- type: latheRecipe
  id: Cartridge44MagnumUranium
  result: Cartridge44MagnumUranium
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20
    Uranium: 10

- type: latheRecipe
  id: Cartridge762x39Uranium
  result: Cartridge762x39Uranium
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20
    Uranium: 10

- type: latheRecipe
  id: Cartridge556x45Uranium
  result: Cartridge556x45Uranium
  category: Ammo
  completetime: 2
  materials:
    Plastic: 15
    Uranium: 10

- type: latheRecipe
  id: MagazineBoxPistolUranium
  result: MagazineBoxPistolUranium
  category: Ammo
  completetime: 5
  materials:
    Plastic: 650
    Uranium: 65

- type: latheRecipe
  id: MagazineBoxMagnumUranium
  result: MagazineBoxMagnumUranium
  category: Ammo
  completetime: 5
  materials:
    Plastic: 1250
    Uranium: 125

- type: latheRecipe
  id: MagazineBox762x39Uranium
  result: MagazineBox762x39Uranium
  category: Ammo
  completetime: 5
  materials:
    Plastic: 1800
    Uranium: 180

- type: latheRecipe
  id: MagazineBoxRifleUranium
  result: MagazineBoxRifleUranium
  category: Ammo
  completetime: 5
  materials:
    Plastic: 950
    Uranium: 95

- type: latheRecipe
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  category: Weapons
  completetime: 6
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  id: MagazineGrenadeEmpty
  result: MagazineGrenadeEmpty
  completetime: 3
  materials:
     Steel: 150
     Plastic: 50

- type: latheRecipe
  id: GrenadeEMP
  result: GrenadeEMP
  completetime: 3
  materials:
     Steel: 150
     Plastic: 100
     Glass: 20

- type: latheRecipe
  id: GrenadeBlast
  result: GrenadeBlast
  completetime: 3
  materials:
     Steel: 150
     Plastic: 100
     Gold: 50

- type: latheRecipe
  id: GrenadeFlash
  result: GrenadeFlash
  completetime: 3
  materials:
     Steel: 150
     Plastic: 100
     Glass: 20
