- type: entity
  parent: GunSafe
  id: GunSafePistolUniversal
  name: mk32 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolUSP
      amount: 2
    - id: MagazineUSP45ACP
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSniperGrand
  name: mark 1 rifle safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSniperGrand
      amount: 2
    - id: SpeedLoader762x39
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeVulcanRifle
  name: L1A1 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleL1A1
      amount: 2
    - id: Magazine762x39
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeAdjutantShotgun
  name: adjutant safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunAdjutant
      amount: 2
    - id: MagazineShotgunBuckshot
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeEnergyGun
  name: energy gun safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGun
      amount: 3

- type: entity
  parent: GunSafe
  id: GunSafeEnergyGunMini
  name: miniature energy gun safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunMini
      amount: 3
