# Armor

- type: entity
  name: spawner
  abstract: true
  id: BaseSpawnerArmor
  parent: BaseSpawner
  components:
  - type: Sprite
    layers:
    - state: blue
    - sprite: Clothing\OuterClothing\Armor\security.rsi
      state: icon

# Armor

- type: entity
  name: spawner
  abstract: true
  id: BaseSpawnerMeleeWeapons
  parent: BaseSpawner
  components:
  - type: Sprite
    layers:
    - state: blue
    - sprite: Objects\Weapons\Melee\combat_knife.rsi
      state: icon
