# Base spawner and lootspawner

- type: entity
  name: spawner
  abstract: true
  id: BaseSpawnerFood
  parent: BaseSpawner
  components:
  - type: Sprite
    layers:
    - state: blue
    - sprite: Objects/Consumable/Food/Tins/meat.rsi
      state: icon

- type: entity
  name: loot spawner
  abstract: true
  id: BaseLootSpawnerFood
  parent: BaseLootSpawner
  components:
  - type: Sprite
    layers:
    - state: blue
    - sprite: Objects/Consumable/Food/Tins/meat.rsi
      state: icon
