# Spawns entities from a loottable once and deletes itself
- type: entity
  name: spawner
  abstract: true
  id: BaseSpawner
  parent: MarkerBase
  components:
  - type: Sprite
    layers:
    - state: blue
  - type: Timer
  - type: LootSpawner
    lootTablePrototype: LootTableTest
    trySpawnOnceAndDelete: true
    guaranteed: true

# Spawns entities from a loottable periodically
- type: entity
  name: loot spawner
  abstract: true
  id: BaseLootSpawnerBasic
  parent: MarkerBase
  components:
  - type: Timer
  - type: LootSpawner
    lootTablePrototype: LootTableTest
    spawnRate: 3 # Per hour

- type: entity
  name: loot spawner
  abstract: true
  id: BaseLootSpawnerRare
  parent: MarkerBase
  components:
  - type: Timer
  - type: LootSpawner
    lootTablePrototype: LootTableTest
    spawnRate: 2 # Per hour

- type: entity
  name: loot spawner
  abstract: true
  id: BaseLootSpawnerEpic
  parent: MarkerBase
  components:
  - type: Timer
  - type: LootSpawner
    lootTablePrototype: LootTableTest
    spawnRate: 2 # Per hour

- type: weightedRandom
  id: LootTableTest
  weights:
    Crowbar: 0.9
    Wrench: 0.1
